export const Emojis = [
    { emoji: "😀", expression: "happy" },
    { emoji: "😁", expression: "beaming" },
    { emoji: "😂", expression: "laughing" },
    { emoji: "🤣", expression: "rolling on floor laughing" },
    { emoji: "😊", expression: "smiling" },
    { emoji: "😇", expression: "innocent" },
    { emoji: "🙂", expression: "slightly smiling" },
    { emoji: "🙃", expression: "upside-down smile" },
    { emoji: "😉", expression: "winking" },
    { emoji: "😍", expression: "love" },
    { emoji: "😘", expression: "kissing" },
    { emoji: "😋", expression: "yummy" },
    { emoji: "😜", expression: "playful" },
    { emoji: "🤪", expression: "crazy" },
    { emoji: "😎", expression: "cool" },
    { emoji: "😢", expression: "crying" },
    { emoji: "😭", expression: "loudly crying" },
    { emoji: "😞", expression: "disappointed" },
    { emoji: "😔", expression: "sad" },
    { emoji: "😡", expression: "angry" },
    { emoji: "🤬", expression: "cursing" },
    { emoji: "😱", expression: "shocked" },
    { emoji: "😨", expression: "fearful" },
    { emoji: "😰", expression: "anxious" },
    { emoji: "😳", expression: "embarrassed" },
    { emoji: "🥵", expression: "hot" },
    { emoji: "🥶", expression: "cold" },
    { emoji: "🤯", expression: "mind blown" },
    { emoji: "🥴", expression: "dizzy" },
    { emoji: "😴", expression: "sleepy" },
    { emoji: "🤢", expression: "nauseous" },
    { emoji: "🤮", expression: "vomiting" },
    { emoji: "🤧", expression: "sick" },
    { emoji: "😷", expression: "mask" },
    { emoji: "🤠", expression: "cowboy happy" },
    { emoji: "🥳", expression: "celebrating" },
    { emoji: "🤔", expression: "thinking" },
    { emoji: "😐", expression: "neutral" },
    { emoji: "😑", expression: "expressionless" },
    { emoji: "😶", expression: "silent" }
  ];
  